// Code generated by dagger. DO NOT EDIT.

package main

import (
	"context"
	"encoding/json"
	"fmt"
	"log/slog"
	"os"
	"sort"

	telemetry "github.com/dagger/otel-go"
	"github.com/vektah/gqlparser/v2/gqlerror"
	"go.opentelemetry.io/otel"
	"go.opentelemetry.io/otel/sdk/resource"
	semconv "go.opentelemetry.io/otel/semconv/v1.40.0"
	"go.opentelemetry.io/otel/trace"

	"dagger/expense-tracker/internal/dagger"

	"github.com/dagger/querybuilder"
)

var dag = dagger.Connect()

func Tracer() trace.Tracer {
	return otel.Tracer("dagger.io/sdk.go")
}

// used for local MarshalJSON implementations
var marshalCtx = context.Background()

// called by main()
func setMarshalContext(ctx context.Context) {
	marshalCtx = ctx
	dagger.SetMarshalContext(ctx)
}

type DaggerObject interface {
	querybuilder.GraphQLMarshaller
	ID(ctx context.Context) (dagger.ID, error)
}

type ExecError = dagger.ExecError

// ptr returns a pointer to the given value.
func ptr[T any](v T) *T {
	return &v
}

// convertSlice converts a slice of one type to a slice of another type using a
// converter function
func convertSlice[I any, O any](in []I, f func(I) O) []O {
	out := make([]O, len(in))
	for i, v := range in {
		out[i] = f(v)
	}
	return out
}

func (r ExpenseTracker) MarshalJSON() ([]byte, error) {
	var concrete struct{}
	return json.Marshal(&concrete)
}

func (r *ExpenseTracker) UnmarshalJSON(bs []byte) error {
	var concrete struct{}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	return nil
}

func (r RunAgainst) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source *dagger.Directory
	}
	concrete.Source = r.Source
	return json.Marshal(&concrete)
}

func (r *RunAgainst) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source *dagger.Directory
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	return nil
}

func (r Terraform) MarshalJSON() ([]byte, error) {
	var concrete struct {
		Source               *dagger.Directory
		Project              string
		Region               string
		OwnerEmail           string
		OAuthClientID        string
		Bucket               string
		AllowUnauthenticated bool
		AccessToken          *dagger.Secret
	}
	concrete.Source = r.Source
	concrete.Project = r.Project
	concrete.Region = r.Region
	concrete.OwnerEmail = r.OwnerEmail
	concrete.OAuthClientID = r.OAuthClientID
	concrete.Bucket = r.Bucket
	concrete.AllowUnauthenticated = r.AllowUnauthenticated
	concrete.AccessToken = r.AccessToken
	return json.Marshal(&concrete)
}

func (r *Terraform) UnmarshalJSON(bs []byte) error {
	var concrete struct {
		Source               *dagger.Directory
		Project              string
		Region               string
		OwnerEmail           string
		OAuthClientID        string
		Bucket               string
		AllowUnauthenticated bool
		AccessToken          *dagger.Secret
	}
	err := json.Unmarshal(bs, &concrete)
	if err != nil {
		return err
	}
	r.Source = concrete.Source
	r.Project = concrete.Project
	r.Region = concrete.Region
	r.OwnerEmail = concrete.OwnerEmail
	r.OAuthClientID = concrete.OAuthClientID
	r.Bucket = concrete.Bucket
	r.AllowUnauthenticated = concrete.AllowUnauthenticated
	r.AccessToken = concrete.AccessToken
	return nil
}

func main() {
	ctx := context.Background()

	// Direct slog to the new stderr. This is only for dev time debugging, and
	// runtime errors/warnings.
	slog.SetDefault(slog.New(slog.NewTextHandler(os.Stderr, &slog.HandlerOptions{
		Level: slog.LevelWarn,
	})))

	if err := dispatch(ctx); err != nil {
		os.Exit(2)
	}
}

func convertError(rerr error) *dagger.Error {
	if gqlErr := findSingleGQLError(rerr); gqlErr != nil {
		dagErr := dag.Error(gqlErr.Message)
		if gqlErr.Extensions != nil {
			keys := make([]string, 0, len(gqlErr.Extensions))
			for k := range gqlErr.Extensions {
				keys = append(keys, k)
			}
			sort.Strings(keys)
			for _, k := range keys {
				val, err := json.Marshal(gqlErr.Extensions[k])
				if err != nil {
					fmt.Println("failed to marshal error value:", err)
				}
				dagErr = dagErr.WithValue(k, dagger.JSON(val))
			}
		}
		return dagErr
	}
	return dag.Error(rerr.Error())
}

func findSingleGQLError(rerr error) *gqlerror.Error {
	switch x := rerr.(type) {
	case *gqlerror.Error:
		return x
	case interface{ Unwrap() []error }:
		return nil
	case interface{ Unwrap() error }:
		return findSingleGQLError(x.Unwrap())
	default:
		return nil
	}
}
func dispatch(ctx context.Context) (rerr error) {
	ctx = telemetry.InitEmbedded(ctx, resource.NewWithAttributes(
		semconv.SchemaURL,
		semconv.ServiceNameKey.String("dagger-go-sdk"),
		// TODO version?
	))
	defer telemetry.Close()

	// A lot of the "work" actually happens when we're marshalling the return
	// value, which entails getting object IDs, which happens in MarshalJSON,
	// which has no ctx argument, so we use this lovely global variable.
	setMarshalContext(ctx)

	fnCall := dag.CurrentFunctionCall()
	defer func() {
		if rerr != nil {
			if err := fnCall.ReturnError(ctx, convertError(rerr)); err != nil {
				fmt.Println("failed to return error:", err, "\noriginal error:", rerr)
			}
		}
	}()

	parentName, err := fnCall.ParentName(ctx)
	if err != nil {
		return fmt.Errorf("get parent name: %w", err)
	}
	fnName, err := fnCall.Name(ctx)
	if err != nil {
		return fmt.Errorf("get fn name: %w", err)
	}
	parentJson, err := fnCall.Parent(ctx)
	if err != nil {
		return fmt.Errorf("get fn parent: %w", err)
	}
	fnArgs, err := fnCall.InputArgs(ctx)
	if err != nil {
		return fmt.Errorf("get fn args: %w", err)
	}

	inputArgs := map[string][]byte{}
	for _, fnArg := range fnArgs {
		argName, err := fnArg.Name(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg name: %w", err)
		}
		argValue, err := fnArg.Value(ctx)
		if err != nil {
			return fmt.Errorf("get fn arg value: %w", err)
		}
		inputArgs[argName] = []byte(argValue)
	}

	result, err := invoke(ctx, []byte(parentJson), parentName, fnName, inputArgs)
	if err != nil {
		return err
	}
	resultBytes, err := json.Marshal(result)
	if err != nil {
		return fmt.Errorf("marshal: %w", err)
	}

	if err := fnCall.ReturnValue(ctx, dagger.JSON(resultBytes)); err != nil {
		return fmt.Errorf("store return value: %w", err)
	}
	return nil
}
func invoke(ctx context.Context, parentJSON []byte, parentName string, fnName string, inputArgs map[string][]byte) (_ any, err error) {
	_ = inputArgs
	switch parentName {
	case "ExpenseTracker":
		switch fnName {
		case "Check":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return nil, (*ExpenseTracker).Check(&parent, ctx, source)
		case "Ci":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var registry string
			if inputArgs["registry"] != nil {
				err = json.Unmarshal([]byte(inputArgs["registry"]), &registry)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg registry", err))
				}
			}
			var auth *dagger.Secret
			if inputArgs["auth"] != nil {
				err = json.Unmarshal([]byte(inputArgs["auth"]), &auth)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg auth", err))
				}
			}
			return nil, (*ExpenseTracker).Ci(&parent, ctx, source, registry, auth)
		case "Deploy":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			var accessToken *dagger.Secret
			if inputArgs["accessToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["accessToken"]), &accessToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg accessToken", err))
				}
			}
			var region string
			if inputArgs["region"] != nil {
				err = json.Unmarshal([]byte(inputArgs["region"]), &region)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg region", err))
				}
			}
			var service string
			if inputArgs["service"] != nil {
				err = json.Unmarshal([]byte(inputArgs["service"]), &service)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg service", err))
				}
			}
			var artifactRegistryRepository string
			if inputArgs["artifactRegistryRepository"] != nil {
				err = json.Unmarshal([]byte(inputArgs["artifactRegistryRepository"]), &artifactRegistryRepository)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg artifactRegistryRepository", err))
				}
			}
			return (*ExpenseTracker).Deploy(&parent, ctx, source, project, accessToken, region, service, artifactRegistryRepository)
		case "Emulator":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var port int
			if inputArgs["port"] != nil {
				err = json.Unmarshal([]byte(inputArgs["port"]), &port)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg port", err))
				}
			}
			var seed bool
			if inputArgs["seed"] != nil {
				err = json.Unmarshal([]byte(inputArgs["seed"]), &seed)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg seed", err))
				}
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			return (*ExpenseTracker).Emulator(&parent, ctx, port, seed, project)
		case "ImageSmokeTest":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ImageSmokeTest(&parent, ctx, source)
		case "ImageTag":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ImageTag(&parent, ctx, source)
		case "ImporterBinary":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ImporterBinary(&parent, source), nil
		case "ImporterImage":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ImporterImage(&parent, source), nil
		case "IntegrationTest":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).IntegrationTest(&parent, ctx, source)
		case "RunAgainst":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).RunAgainst(&parent, source), nil
		case "ServerBinary":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ServerBinary(&parent, source), nil
		case "ServerImage":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return (*ExpenseTracker).ServerImage(&parent, source), nil
		case "TemplCheck":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			return nil, (*ExpenseTracker).TemplCheck(&parent, ctx, source)
		case "Terraform":
			var parent ExpenseTracker
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var source *dagger.Directory
			if inputArgs["source"] != nil {
				err = json.Unmarshal([]byte(inputArgs["source"]), &source)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg source", err))
				}
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			var region string
			if inputArgs["region"] != nil {
				err = json.Unmarshal([]byte(inputArgs["region"]), &region)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg region", err))
				}
			}
			var ownerEmail string
			if inputArgs["ownerEmail"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ownerEmail"]), &ownerEmail)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ownerEmail", err))
				}
			}
			var oauthClientId string
			if inputArgs["oauthClientID"] != nil {
				err = json.Unmarshal([]byte(inputArgs["oauthClientID"]), &oauthClientId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg oauthClientID", err))
				}
			}
			var stateBucket string
			if inputArgs["stateBucket"] != nil {
				err = json.Unmarshal([]byte(inputArgs["stateBucket"]), &stateBucket)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg stateBucket", err))
				}
			}
			var allowUnauthenticated bool
			if inputArgs["allowUnauthenticated"] != nil {
				err = json.Unmarshal([]byte(inputArgs["allowUnauthenticated"]), &allowUnauthenticated)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg allowUnauthenticated", err))
				}
			}
			var accessToken *dagger.Secret
			if inputArgs["accessToken"] != nil {
				err = json.Unmarshal([]byte(inputArgs["accessToken"]), &accessToken)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg accessToken", err))
				}
			}
			return (*ExpenseTracker).Terraform(&parent, source, project, region, ownerEmail, oauthClientId, stateBucket, allowUnauthenticated, accessToken), nil
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "RunAgainst":
		switch fnName {
		case "Local":
			var parent RunAgainst
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			var port int
			if inputArgs["port"] != nil {
				err = json.Unmarshal([]byte(inputArgs["port"]), &port)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg port", err))
				}
			}
			var project string
			if inputArgs["project"] != nil {
				err = json.Unmarshal([]byte(inputArgs["project"]), &project)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg project", err))
				}
			}
			var ownerEmail string
			if inputArgs["ownerEmail"] != nil {
				err = json.Unmarshal([]byte(inputArgs["ownerEmail"]), &ownerEmail)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg ownerEmail", err))
				}
			}
			var seed bool
			if inputArgs["seed"] != nil {
				err = json.Unmarshal([]byte(inputArgs["seed"]), &seed)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg seed", err))
				}
			}
			var oauthClientId string
			if inputArgs["oauthClientID"] != nil {
				err = json.Unmarshal([]byte(inputArgs["oauthClientID"]), &oauthClientId)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg oauthClientID", err))
				}
			}
			var oauthClientSecret *dagger.Secret
			if inputArgs["oauthClientSecret"] != nil {
				err = json.Unmarshal([]byte(inputArgs["oauthClientSecret"]), &oauthClientSecret)
				if err != nil {
					panic(fmt.Errorf("%s: %w", "failed to unmarshal input arg oauthClientSecret", err))
				}
			}
			return (*RunAgainst).Local(&parent, ctx, port, project, ownerEmail, seed, oauthClientId, oauthClientSecret)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	case "Terraform":
		switch fnName {
		case "Apply":
			var parent Terraform
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Terraform).Apply(&parent, ctx)
		case "Output":
			var parent Terraform
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Terraform).Output(&parent, ctx)
		case "Plan":
			var parent Terraform
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Terraform).Plan(&parent, ctx)
		case "StateBucket":
			var parent Terraform
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Terraform).StateBucket(&parent, ctx)
		case "Validate":
			var parent Terraform
			err = json.Unmarshal(parentJSON, &parent)
			if err != nil {
				panic(fmt.Errorf("%s: %w", "failed to unmarshal parent object", err))
			}
			return (*Terraform).Validate(&parent, ctx)
		default:
			return nil, fmt.Errorf("unknown function %s", fnName)
		}
	default:
		return nil, fmt.Errorf("unknown object %s", parentName)
	}
}
